### PR TITLE
Remove console.log

### PR DESCRIPTION
**Pull request by chris-jamieson**
Great package, thank you! Only minor annoyance is the `console.log()` statement which appears during build. This is particularly annoying when you have a large table and you're using `hexo server`.

### CODE REVIEW

**Comment by jorgeabad** [comment]
Thanks for the collaboration

**Comment by chris-jamieson** [comment]
That's great @jorgeabad - thanks for merging the PR. Do you have time to publish the updated version to NPM?

**Comment by jorgeabad** [comment]
Hi @jamiesoncj, the package has been updated in npm to v1.0.5, thanks.

**Comment by chris-jamieson** [comment]
Awesome, thank you @jorgeabad - appreciated!

**Pull request merged**
